language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-22
sudo: required
install:
  - echo "Install stage"
  - sudo curl --silent --location https://deb.nodesource.com/setup_0.12 | sudo bash -
  - sudo apt-get install --yes nodejs
  - sudo npm install -g gulp bower ionic cordova
  - sudo npm install
script:
  - echo "Loading Ionic stuff"
  - ionic state restore
  - gulp build.android
after_failure:
- echo "Error happened"
after_script:
- echo "Script has been finished"
